openapi: 3.0.1
info:
  title: Tufin
  version: "4.0"
servers:
- url: https://localhost:8080
components:
  parameters:
    groupId:
      in: query
      name: groupId
      required: true
      schema:
        type: string
  schemas:
    GroupView:
      type: object
      properties:
        data:
          type: object
          properties:
            created:
              type: string
              format: date-time
              readOnly: true
            id:
              type: string
              readOnly: true
            name:
              type: string
            description:
              type: string
          required:
            - name
paths:
  /api/v1.1/groups:
    post:
      tags:
       - Group
      operationId: createOneGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupView'
        description: Creates one project.
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupView'
          description: Created
      summary: Create a Project
