name: go
on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  oasdiff:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Get prev commit
      run: echo "PREV_COMMIT=$(git --no-pager log -n1 | grep commit | cut -d' ' -f2)" >> $GITHUB_ENV

    - name: Run diff
      run: docker run --rm -t -v $(pwd)/:/data:ro tufin/oasdiff changelog https://raw.githubusercontent.com/reuvenharrison/oas/$PREV_COMMIT/simple.yaml /data/simple.yaml -f githubactions

