name: go
on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  oasdiff:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Git Log
      run: git log -n2

    - name: Get prev commit
      run: echo "PREV_COMMIT=$(git --no-pager log -n2 | grep commit | tail -n1 | cut -d' ' -f2)" >> $GITHUB_ENV
      
    - name: Get prev file
      run: echo "PREV_FILE=$(echo https://raw.githubusercontent.com/reuvenharrison/oas/${{ env.PREV_COMMIT }}/simple.yaml)" >> $GITHUB_ENV

    - name: Run diff
      run: docker run --rm -t -v $(pwd)/:/data:ro tufin/oasdiff changelog ${{ env.PREV_FILE }} /data/simple.yaml -f githubactions

