name: oasdiff PR comment

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Fetch base branch
      run: git fetch --depth=1 origin ${{ github.base_ref }}

    - name: Post oasdiff PR comment
      uses: oasdiff/oasdiff-action/pr-comment@v0.0.37
      with:
        base: 'origin/${{ github.base_ref }}:multi-file/openapi.yaml'
        revision: 'HEAD:multi-file/openapi.yaml'
        oasdiff-token: ${{ secrets.OASDIFF_TOKEN }}
